name: Deploy

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: yarn
        run: |
          yarn
      - name: App Deploy
        run: |
          yarn run latest
